<a href="https://colab.research.google.com/github/peacewhile/PHM-Learning-Task/blob/main/NGAFID_DATASET_DASK_EXAMPLE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INSTALL PREREQ

In [1]:
!python -m pip install "dask[dataframe]"

Requirement already satisfied: dask[dataframe] in /usr/local/lib/python3.12/dist-packages (2026.1.1)
Requirement already satisfied: click>=8.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (8.3.1)
Requirement already satisfied: cloudpickle>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (3.1.2)
Requirement already satisfied: fsspec>=2021.09.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (2025.3.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (26.0)
Requirement already satisfied: partd>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (1.4.2)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (6.0.3)
Requirement already satisfied: toolz>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (0.12.1)
Requirement already satisfied: pandas>=2.0 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (2.2.2)
Requirement already satisfied: pyarrow>=14.0.1 in /usr/local/lib/python3.12/dist-packages (from dask[dataframe]) (18.1.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2.0->dask[dataframe]) (2025.3)
Requirement already satisfied: locket in /usr/local/lib/python3.12/dist-packages (from partd>=1.4.0->dask[dataframe]) (1.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=2.0->dask[dataframe]) (1.17.0)

In [2]:
!git clone https://github.com/hyang0129/NGAFIDDATASET.git

!(cd NGAFIDDATASET ; git checkout main; git reset --hard HEAD; git pull)
!(cd NGAFIDDATASET ; pip install -r requirements.txt -q)

Cloning into 'NGAFIDDATASET'...
remote: Enumerating objects: 120, done.
remote: Counting objects: 100% (120/120), done.
remote: Compressing objects: 100% (99/99), done.
remote: Total 120 (delta 52), reused 64 (delta 18), pack-reused 0 (from 0)
Receiving objects: 100% (120/120), 253.61 KiB | 2.01 MiB/s, done.
Resolving deltas: 100% (52/52), done.
Already on 'main'
Your branch is up to date with 'origin/main'.
HEAD is now at fa72386 Update README.md
Already up to date.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.9/91.9 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 45.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.6/63.6 kB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 26.9 MB/s eta 0:00:00

# IMPORT DEPENDENCIES

In [9]:
!pip install gdown -q
import gdown
import os

FILE_ID  = '1I6Hdf0M5PUQnOzlESklex7k31vAR9OU5'
DATA_DIR = '/content/all_flights'

if not os.path.exists(DATA_DIR):
    gdown.download(
        f'https://drive.google.com/uc?id={FILE_ID}',
        '/content/all_flights.tar.gz',
        quiet=False
    )
    !tar -xzf /content/all_flights.tar.gz -C /content/
    print("数据集下载并解压完成")
else:
    print("数据集已存在，跳过下载")

Downloading...
From (original): https://drive.google.com/uc?id=1I6Hdf0M5PUQnOzlESklex7k31vAR9OU5
From (redirected): https://drive.google.com/uc?id=1I6Hdf0M5PUQnOzlESklex7k31vAR9OU5&confirm=t&uuid=04fdee91-4035-4c81-afbf-fee753d8b68b
To: /content/all_flights.tar.gz
100%|██████████| 4.29G/4.29G [00:59<00:00, 72.6MB/s]

数据集下载并解压完成

In [4]:
# --- 1. 解决 Python 3.12 兼容性 (imp 补丁) ---
import sys
import types
if 'imp' not in sys.modules:
    fake_imp = types.ModuleType('imp')
    fake_imp.find_module = lambda *args: None
    fake_imp.load_module = lambda *args: None
    sys.modules['imp'] = fake_imp
    print("🛠️ 虚拟 imp 注入成功")

# --- 2. 加载并设置 autoreload (只在这里写一次) ---
try:
    %load_ext autoreload
    %autoreload 2
    print("✅ Autoreload 配置完成")
except:
    print("⚠️ Autoreload 之前已加载过")

# --- 3. 添加数据集路径 ---
dataset_path = '/content/NGAFIDDATASET'
if dataset_path not in sys.path:
    sys.path.append(dataset_path)
    print(f"🚀 路径已挂载: {dataset_path}")

🛠️ 虚拟 imp 注入成功
⚠️ Autoreload 之前已加载过
🚀 路径已挂载: /content/NGAFIDDATASET

In [10]:
import dask.dataframe as dd

flight_data_df = dd.read_parquet('/content/all_flights/one_parq')

flight_header_df = pd.read_csv('/content/all_flights/flight_header.csv', index_col = 'Master Index')

In [11]:
flight_data_df

Dask DataFrame Structure:
                   volt1    volt2     amp1     amp2    FQtyL    FQtyR E1 FFlow  E1 OilT  E1 OilP   E1 RPM  E1 CHT1  E1 CHT2  E1 CHT3  E1 CHT4  E1 EGT1  E1 EGT2  E1 EGT3  E1 EGT4      OAT      IAS     VSpd   NormAc   AltMSL timestep cluster
npartitions=401
                 float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64  float64    int64  string
                     ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...     ...
...                  ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...     ...
                     ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...     ...
                     ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...      ...     ...
Dask Name: read_parquet, 1 expression
Expr=ReadParquetFSSpec(5f38fd5)

In [12]:
flight_data_df.head(5)

,volt1,volt2,amp1,amp2,FQtyL,FQtyR,E1 FFlow,E1 OilT,E1 OilP,E1 RPM,...,E1 EGT2,E1 EGT3,E1 EGT4,OAT,IAS,VSpd,NormAc,AltMSL,timestep,cluster
Master Index,,,,,,,,,,,,,,,,,,,,,
1,28.8,NaN,0.8,NaN,48.89,44.06,13.28,168.55,82.51,2519.7,...,1317.44,1298.97,1322.83,12.8,144.89,29.61,0.01,3010.7,3151,c_28
1,28.8,NaN,0.8,NaN,48.93,44.06,13.31,168.60,82.51,2519.4,...,1316.64,1300.68,1322.15,12.8,144.53,49.78,-0.00,3011.3,3150,c_28
1,28.8,NaN,0.9,NaN,48.96,44.06,13.36,168.65,82.51,2520.3,...,1317.20,1301.05,1323.12,12.8,144.15,58.68,-0.01,3011.8,3149,c_28
1,28.8,NaN,0.7,NaN,48.86,44.06,13.30,168.64,82.51,2519.3,...,1317.73,1302.14,1321.93,12.8,143.79,47.31,-0.00,3012.2,3148,c_28
1,28.8,NaN,0.6,NaN,48.87,44.06,13.30,168.65,82.51,2518.8,...,1318.00,1308.52,1316.99,12.8,143.45,36.05,-0.01,3012.3,3147,c_28

In [13]:
flight_header_df.head(5)

,before_after,date_diff,flight_length,label,hierarchy,number_flights_before
Master Index,,,,,,
1,before,-1,4723.0,intake gasket leak/damage,NaN,0
2,before,-2,4649.0,intake gasket leak/damage,NaN,3
3,same,0,40.0,intake gasket leak/damage,NaN,-1
4,before,0,14.0,intake gasket leak/damage,NaN,0
5,same,0,683.0,intake gasket leak/damage,NaN,-1